"""
DEPRECATED - this file is intentionally empty.

The previous version of TrustPulse used this script to insert synthetic data
into a mock OpenEMR database. That approach violated the system's non-negotiable
rule that TrustPulse must only consume audit logs generated by a real OpenEMR
instance, not fabricated ones.

To generate demo activity, use the dedicated demo scenario generator instead:

    TRUSTPULSE_ALLOW_OPENEMR_DEMO_WRITE=true \\
    python tools/openemr_demo_scenario_generator.py

That tool creates demo patients and access activity INSIDE a real (lab)
OpenEMR instance, which then generates real audit log entries that TrustPulse
reads through its normal read-only connector.

See tools/openemr_demo_scenario_generator.py and README.md for details.
"""
raise RuntimeError(
    "simulation/seed_data.py is deprecated and must not be called. "
    "Use tools/openemr_demo_scenario_generator.py for demo data generation."
)
