from datetime import datetime, timedelta

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session

from db.models import ComplianceCalendarItem
from db.session import get_tp_session
from engine.compliance import (
    compute_compliance_health_score,
    compute_minimum_necessary,
    seed_compliance_calendar,
)
from api.auth import get_current_user, require_permission, TrustPulseUser

router = APIRouter(prefix="/api/compliance", tags=["compliance"])

ITEM_FREQUENCIES_DAYS = {
    "AUDIT_REVIEW": 30,
    "RISK_ANALYSIS": 365,
    "TRAINING": 365,
    "BAA_REVIEW": 365,
}


@router.get("/health")
def compliance_health(
    db: Session = Depends(get_tp_session),
    _current: TrustPulseUser = Depends(get_current_user),
):
    return compute_compliance_health_score(db)


@router.get("/minimum_necessary")
def minimum_necessary(
    db: Session = Depends(get_tp_session),
    _current: TrustPulseUser = Depends(get_current_user),
):
    return {"report": compute_minimum_necessary(db)}


@router.get("/calendar")
def calendar(
    db: Session = Depends(get_tp_session),
    _current: TrustPulseUser = Depends(get_current_user),
):
    seed_compliance_calendar(db)
    items = db.query(ComplianceCalendarItem).order_by(ComplianceCalendarItem.next_due).all()
    now = datetime.utcnow()
    return {
        "items": [
            {
                "id": i.id,
                "item_type": i.item_type,
                "hipaa_provision": i.hipaa_provision,
                "last_completed": i.last_completed.isoformat() if i.last_completed else None,
                "next_due": i.next_due.isoformat() if i.next_due else None,
                "status": i.status,
                "days_until_due": (i.next_due - now).days if i.next_due else None,
                "notes": i.notes,
            }
            for i in items
        ]
    }


class CalendarCompleteRequest(BaseModel):
    notes: str = ""


@router.put("/calendar/{item_id}/complete")
def mark_calendar_complete(
    item_id: int,
    req: CalendarCompleteRequest,
    db: Session = Depends(get_tp_session),
    current: TrustPulseUser = Depends(require_permission("disposition")),
):
    item = db.get(ComplianceCalendarItem, item_id)
    if not item:
        raise HTTPException(status_code=404, detail="Calendar item not found")

    now = datetime.utcnow()
    freq = ITEM_FREQUENCIES_DAYS.get(item.item_type, 365)
    item.last_completed = now
    item.next_due = now + timedelta(days=freq)
    item.status = "ON_TRACK"
    if req.notes:
        item.notes = req.notes
    db.commit()

    return {"item_id": item_id, "next_due": item.next_due.isoformat(), "status": "ON_TRACK"}


@router.get("/summary_report", response_class=HTMLResponse)
def summary_report(
    db: Session = Depends(get_tp_session),
    current: TrustPulseUser = Depends(require_permission("export")),
):
    import os
    clinic = os.environ.get("CLINIC_NAME", "Healthcare Clinic")
    health = compute_compliance_health_score(db)
    mn = compute_minimum_necessary(db)
    seed_compliance_calendar(db)
    calendar_items = db.query(ComplianceCalendarItem).all()
    now = datetime.utcnow()

    rows = "".join(
        f"<tr><td>{r['user_name']}</td><td>{r['role']}</td><td>{r['user_daily_avg']}</td>"
        f"<td>{r['peer_daily_avg']}</td><td>{r['ratio']}x</td>"
        f"<td style='color:{'red' if r['status']=='ACTION' else 'orange' if r['status']=='REVIEW' else 'green'}'>"
        f"{r['status']}</td></tr>"
        for r in mn
    )
    cal_rows = "".join(
        f"<tr><td>{i.item_type}</td><td>{i.hipaa_provision}</td>"
        f"<td>{i.last_completed.strftime('%b %d, %Y') if i.last_completed else '-'}</td>"
        f"<td>{i.next_due.strftime('%b %d, %Y') if i.next_due else '-'}</td>"
        f"<td style='color:{'red' if i.status=='OVERDUE' else 'orange' if i.status=='DUE_SOON' else 'green'}'>"
        f"{i.status}</td></tr>"
        for i in calendar_items
    )

    html = f"""<!DOCTYPE html><html><head><meta charset='utf-8'>
<title>HIPAA Compliance Summary - {clinic}</title>
<style>body{{font-family:sans-serif;max-width:900px;margin:40px auto;color:#111}}
h1{{border-bottom:3px solid #0A2540;padding-bottom:8px}}
h2{{color:#0A2540;margin-top:32px}}
.score{{font-size:3em;font-weight:bold;color:{'#00B37D' if health['color']=='green' else '#DD6B20' if health['color']=='yellow' else '#E53E3E'}}}
table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #ddd;padding:6px 10px;text-align:left}}th{{background:#f5f5f5}}</style>
</head><body>
<h1>HIPAA Annual Compliance Summary</h1>
<p><b>Facility:</b> {clinic} &nbsp;|&nbsp; <b>Generated:</b> {now.strftime('%B %d, %Y %H:%M UTC')} &nbsp;|&nbsp; <b>Generated by:</b> {current.display_name} ({current.role})</p>
<p><b>Report Period:</b> Last 30 days</p>
<div style='background:#FFF3CD;border:1px solid #F59E0B;padding:12px 16px;border-radius:6px;margin:16px 0;font-size:.85em;'>
  <b>Governance Decision-Support Artifact.</b> This report is based on TrustPulse-observed OpenEMR telemetry only.
  It is not a legal determination of HIPAA compliance, breach status, or notification obligation.
  Final determinations require qualified privacy and compliance review.
</div>
<h2>Compliance Health Score</h2>
<p class='score'>{health['score']}/100 - {health['grade']}</p>
<p>{health['top_issue']}</p>
<h2>HIPAA Compliance Calendar</h2>
<table><tr><th>Item</th><th>Provision</th><th>Last Completed</th><th>Next Due</th><th>Status</th></tr>
{cal_rows}</table>
<h2>Minimum Necessary Access - §164.502(b)</h2>
<table><tr><th>User</th><th>Role</th><th>Avg/Day</th><th>Peer Avg</th><th>Ratio</th><th>Status</th></tr>
{rows}</table>
<p style='margin-top:40px;font-size:.8em;color:#666'>Generated by TrustPulse - read-only governance oversight system. No OpenEMR data was modified.</p>
</body></html>"""

    return HTMLResponse(
        content=html,
        headers={"Content-Disposition": f'attachment; filename="hipaa_summary_{now.strftime("%Y%m%d")}.html"'},
    )
